### PR TITLE
apacheKakfa 3.6.1 and 3.5.0 -> 3.5.2

### PR DESCRIPTION
**Pull request by daniel-awake**

### CODE REVIEW

**Comment by daniel-awake** [comment]
I don't know how to verify/validate this-- is there an appropriate nix command to try it?

**Comment by bacchanalia** [comment]
Can you split up adding 3.6 and making it the default? I'd like the patch adding 3.6 to get up streamed.

**Comment by daniel-awake** [comment]
@bacchanalia hopefully this is close to what you were thinking. Let me know if you need anything else.

**Comment by bacchanalia** [comment]
Did you still want to update the default kafka version here or are you doing it in end-to-end instead?

**Comment by daniel-awake** [comment]
> Did you still want to update the default kafka version here or are you doing it in end-to-end instead?

Oh, if you don't mind, I'll do it here. I was thinking you might have wanted it in a separate PR.

**Comment by bacchanalia** [comment]
We should squash merge this one and do that in a seperate PR 👍

**Review by bacchanalia — APPROVED** [review]

**Comment by bacchanalia** [comment]
Squash merge isn't enabled for this repo, so I think you should just squash them manually, and then the second commit can also be on this PR since the PR isn't getting squashed.

**Comment by daniel-awake** [comment]
I don't have merge permissions. @bacchanalia do you know who does?

**Comment by bacchanalia** [comment]
Sorry, I didn't notice the first commit was a cherry pick. This is good.

**Pull request merged**
