### PR TITLE
rustc, cargo: always build on big-sur

### PR DESCRIPTION
**Pull request by jsoo1**
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by evanrelf — COMMENTED** [review]
Is it possible to add these required system features in an overlay in `end-to-end`? I feel like it doesn't belong in the Nixpkgs fork.

**Comment by evanrelf** [comment]
> I agree, but it's quite onerous to override them. I tried for quite a while.

Ah okay, dang

**Comment by jsoo1** [comment]
@evanrelf For a little more context on why it's difficult, it's because the rustc/cargo definitions are part of the `rustPlatform` attrs which I just found very hard to effectively override.

**Comment by Gabriella439** [comment]
Also, once we upgrade to a newer Nixpkgs I presume that we can drop the Big Sur mandatory feature since I believe newer versions of Nixpkgs don't require bootstrapping things on Big Sur

**Comment by jsoo1** [comment]
> Also, once we upgrade to a newer Nixpkgs I presume that we can drop the Big Sur mandatory feature since I believe newer versions of Nixpkgs don't require bootstrapping things on Big Sur

I agree with that, too. I think if we are careful when forward-porting patches from `awake-21.05` that should be pretty easy to spot? Does it deserve some commentary?

**Comment by jsoo1** [comment]
Ok thank you!

**Pull request merged**
