### PR TITLE
mark trivial derivations with __snowkiteOmissible

### PR DESCRIPTION
**Pull request by bacchanalia**

### CODE REVIEW

**Review by jsoo1 — COMMENTED** [review]
Can we override mkDerivation to do something like:
```
mkDerivation { ... }
// lib.optionalAttrs (preferLocalBuild && !allowSubstitutes) { __buildkiteOmissible = true; }
```
?

**Comment by bacchanalia** [comment]
Not without rebuilding basically everything. Since we need __snowkiteOmissible to be in the derivation instead of just the meta, it will infect everything upstream of it.

**Comment by jsoo1** [comment]
> Not without rebuilding basically everything. Since we need __snowkiteOmissible to be in the derivation instead of just the meta, it will infect everything upstream of it.

I hear you and agree. But if we use `optionalAttrs` then the attribute gets omitted from the derivation, right?

**Comment by bacchanalia** [comment]
Yes, but if we add it to any transitive dependency of a derivation, it will change the derivation path.

**Comment by jsoo1** [comment]
Ok, maybe I don't know what your concern is.

**Review by jsoo1 — APPROVED** [review]

**Pull request merged**
